# Site settings
title: SudoPlay Games
email: your-email@domain.com
description: "SudoPlay Games is a small, independent game studio located in Oregon, USA."
baseurl: ""
url: "http://localhost:4000"
twitter_username: sudoplaygames
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
